# Generated by Django 4.0.6 on 2022-07-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_question_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='ques',
            new_name='question',
        ),
    ]
